### ISSUE TITLE
Unable to set transparent badge

### ISSUE THREAD

**Issue by aideric** [yako-dev/flutter_badges#100]
## Environment

**Package version:**  3.0.2 
**Platform:** Any 
**Device information:**  Any 

## Description

**Expected behavior:**
Can show transparent badge
**Current behavior:**
White badge 

## Steps to reproduce
1. Download the example app
2. Change the [_shoppingCartBadge](https://github.com/yako-dev/flutter_badges/blob/d5db6fc67fdf1de7553686988ef6bc4a44062d97/example/lib/main.dart#L116-L133) to the following
```dart
  Widget _shoppingCartBadge() {
    return badges.Badge(
      position: badges.BadgePosition.topEnd(top: 0, end: 3),
      badgeAnimation: badges.BadgeAnimation.slide(
          // disappearanceFadeAnimationDuration: Duration(milliseconds: 200),
          // curve: Curves.easeInCubic,
          ),
      showBadge: _showCartBadge,
      badgeStyle: badges.BadgeStyle(
        badgeColor: Colors.transparent,
      ),
      badgeContent: Text(
        _cartBadgeAmount.toString(),
        style: TextStyle(color: Colors.black),
      ),
      child: IconButton(icon: Icon(Icons.shopping_cart), onPressed: () {}),
    );
  }
```
3. build the app

## Images   
The upper right shopping cart
![Simulator Screen Shot - iPhone 14 Pro Max - 2023-02-06 at 11 59 10](https://user-images.githubusercontent.com/36286481/216880819-f2db7be6-6eba-4495-a880-4d92ea180383.png)

## Fix
https://github.com/yako-dev/flutter_badges/blob/d5db6fc67fdf1de7553686988ef6bc4a44062d97/lib/src/badge.dart#L190-L192
```dart
Material(
  shape: border,
  elevation: widget.badgeStyle.elevation,
  type: MaterialType.transparency,
```
Using the MaterialType.transparency can set the Material widget to transparent background

**Comment by ff56k** [comment]
I found that the new badge shapes, twitter and instagram allows transparency as per normal while square and circle do not.

**Comment by yadaniyil** [comment]
Thanks, @aideric and @ff56k. The fix is in the master branch already and will be published soon.

**Comment by yadaniyil** [comment]
Hey @hbock-42, I just uploaded version 3.0.3 with fix for transparent badge

**Comment by hbock-42** [comment]
@yadaniyil Thx a lot, working perfectly

**Comment by luis901101** [comment]
Hi, using `type: MaterialType.transparency` opaques the `elevation: widget.badgeStyle.elevation` which defaults to 2. Maybe `BadgeStyle` could support a new property like `allowTransparency` then:
`type: widget.badgeStyle.allowTransparency ? MaterialType.transparency : MaterialType.canvas`.
