### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by aliaktas-tr** [yako-dev/flutter_badges#101]
## Describe your question
Because weedus depends on easy_sidemenu ^0.4.1 which depends on badges ^2.0.2, badges ^2.0.2 is required.
So, because weedus depends on badges ^3.0.2, version solving failed.

**Comment by yadaniyil** [comment]
@aliaktas-tr try to place badges into the dependency_overrides, not the dependencies, like this:
```
dependency_overrides:
  badges: ^3.0.2
```
If it doesn't work for you, then ask easy_sidemenu to migrate to the new version of badges.

**Comment by aliaktas-tr** [comment]
> @aliaktas-tr try to place badges into the dependency_overrides, not the dependencies, like this:
> 
> ```
> dependency_overrides:
>   badges: ^3.0.2
> ```
> 
> If it doesn't work for you, then ask easy_sidemenu to migrate to the new version of badges.

Thank you.
