### ISSUE TITLE
Is it possible to do a typing animation?

### ISSUE THREAD

**Issue by AdrKacz** [yako-dev/flutter_badges#104]
## Environment
Apple / Android, `sdk: ">=2.17.0 <3.0.0"`

## Describe your question
I can see there are multiple ways of doing animation with the Badges. However, they are all about the overall widget. Will it be possible to design a typing animation with your packages (_three dot shading in and out in sequence_)

_Thank you for your excellent package, it saves a lot of engineering time for my personal projects 🎉_

**Comment by yadaniyil** [comment]
Hey @AdrKacz. This is out of scope of this package, but I think you can easily implement it with this package: https://pub.dev/packages/animated_text_kit, as you can pass any widget into the badge content.
