### ISSUE TITLE
Package "Badge" widget is conflicting with the material design Badge widget

### ISSUE THREAD

**Issue by csof3cen** [yako-dev/flutter_badges#105]

**Comment by csof3cen** [comment]
[Flutter 3.7](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c) introduced the Badge component with the material 3 support. That class is conflicting with the Badge class from this package.

What is did :
`import 'package:badges/badges.dart' as badger;`

And thenn, use it like this :
`badger.Badge()`

I don't know if its an option to change the entire package classes names since it's [widely used](https://www.youtube.com/watch?v=_CIHLJHVoN8&ab_channel=Flutter).

**Comment by yadaniyil** [comment]
Hey @csof3cen. Thanks for the issue. I had to update the package readme so everyone uses the 
```
import 'package:badges/badges.dart' as badges;
badges.Badge()
```
format.

**Comment by csof3cen** [comment]
Thanks !
