### ISSUE TITLE
Badge in AppBar

### ISSUE THREAD

**Issue by antoniocali** [yako-dev/flutter_badges#14]
Hello. I don't know if I should change some properties but I didn't find anything.
If I use Badge in the AppBar inside the actions, the Icon it's totally on different alignment compare to others.

Just a Icon:
![immagine](https://user-images.githubusercontent.com/15616093/72467609-8e1f4180-37db-11ea-8546-aed82a5a39f5.png)

If I use the Badge:
![immagine](https://user-images.githubusercontent.com/15616093/72467661-aee79700-37db-11ea-8d04-6b2a43c217a9.png)

Version: 
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (5 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
badges: ^1.1.0

**Comment by yadaniyil** [comment]
@antoniocali, fixed in  **badges:** ^1.1.1
