### ISSUE TITLE
There should be a way to remove badge's drop shadow

### ISSUE THREAD

**Issue by ramtinq** [yako-dev/flutter_badges#17]
Thanks for this great package. I wanted to know if there is a way to remove the badge's drop shadow. Or if there's no way currently, I ask you to please implement a way to make it optional.

**Comment by RusKryzhanovskiy** [comment]
Hi, @ramtinq!
I'm glad you like our package. 
In order to remove shadows, you need to add "elevation: 0".
For example:
```dart
Badge(
    elevation: 0,
    ...
),
```
