### ISSUE TITLE
BadgePosition Constants

### ISSUE THREAD

**Issue by awhitford** [yako-dev/flutter_badges#18]
_Great package!_

I was just curious if this was on purpose:

https://github.com/yako-dev/flutter_badges/blob/7c6821aff85c8438f405f80e4bd084ecbf1cca3e/lib/src/badge_position.dart#L10

Should the 5 be an 8, like the rest?

Also, it would be great to have a little documentation on this class because I am unclear on what these relative coordinates are precisely relative to.  (I just kept experimenting with a bunch of values and landed on -20 for my case -- documentation may have made the deduction faster.)

**Comment by RusKryzhanovskiy** [comment]
@awhitford sorry for the delay. 
These numbers - distance from the specified side to the Badge.

### Example 1 
```dart
position: BadgePosition.topStart(top: 10, start: 0),
```
![Screenshot 2020-12-07 at 18 39 16](https://user-images.githubusercontent.com/16175106/101378224-836e0f00-38bb-11eb-8cf1-0fa04c4de3ec.png)
### Example 2
```dart
position: BadgePosition.topStart(top: 0, start: 10),
```
![Screenshot 2020-12-07 at 18 39 41](https://user-images.githubusercontent.com/16175106/101378276-92ed5800-38bb-11eb-9cd7-fde10cf5ac28.png)
### Example 3
```dart
position: BadgePosition.topStart(top: 10, start: 10),
```
![Screenshot 2020-12-07 at 18 39 55](https://user-images.githubusercontent.com/16175106/101378296-9aacfc80-38bb-11eb-97ae-66dd0d0cbb88.png)
### Example 4
```dart
position: BadgePosition.topStart(top: -10, start: -10),
```
![Screenshot 2020-12-07 at 18 49 43](https://user-images.githubusercontent.com/25484375/101379485-fa57d780-38bc-11eb-95cf-1a27d0cb404d.png)
## Default value

![Screenshot 2020-12-07 at 18 40 20](https://user-images.githubusercontent.com/16175106/101378348-a8fb1880-38bb-11eb-89bd-afd1d761a408.png)

We have picked up the values at which your Badge looks good by default. 

We will certainly write the documentation in the future. Thank you for your appeal!
