### ISSUE TITLE
All transparent without shadow and support for images.

### ISSUE THREAD

**Issue by yona-asael** [yako-dev/flutter_badges#19]
Hi, i like to much this package asome is my new favorite base package for badges.

But the problem me and maybe other people in the future we will have is if we can put invisble or transparent style because can i put the background color in transparent but the problem is the shadow stay in the backgroud and nothing matter what i do that shadow i cant remove if they help me with other widget with another solucion and i ask about the support for only images this package could be have in the future.

Thank so much and i attach image about the shadow i had in the badge

<img src="https://i.ibb.co/92S7PSg/Transparent.png" alt="Transparent" border="0">

**Comment by enricobenedos** [comment]
Me too. I'm trying to set transparent background but at the moment it is not possible

**Comment by RusKryzhanovskiy** [comment]
@yona-asael @enricobenedos sorry for the delay.
You need to set `elevation: 0` for your Badge. This will remove the "black shadow". 
## Default elevation
![Screenshot 2020-12-07 at 18 58 21](https://user-images.githubusercontent.com/25484375/101380442-2de73180-38be-11eb-8fd3-95448182362b.png)
## Zero elevation
![Screenshot 2020-12-07 at 18 58 38](https://user-images.githubusercontent.com/25484375/101380482-38093000-38be-11eb-95eb-75227fd9a150.png)
