### ISSUE TITLE
not working with flutter 1.19

### ISSUE THREAD

**Issue by softmarshmallow** [yako-dev/flutter_badges#21]
```
../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart:83:19: Error: The getter 'Overflow' isn't defined for the class 'BadgeState'.
 - 'BadgeState' is from 'package:badges/src/badge.dart' ('../../../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Overflow'.
        overflow: Overflow.visible,
                  ^^^^^^^^
```

doctor

```
Flutter 1.19.0-2.0.pre.213 • channel master • https://github.com/flutter/flutter.git
Framework • revision eb1a6efe16 (9 hours ago) • 2020-05-30 21:58:02 -0400
Engine • revision 923687f0e7
Tools • Dart 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.213, on Mac OS X 10.15.3 19D76, locale en-KR)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)


```

**Comment by emrekaranfil** [comment]
I'm having this problem.

[https://prnt.sc/sr2vl9](url)

**Comment by Gintasz** [comment]
I can confirm this. Doesn't compile for web.

> gintas-mac:domukpizzaapp gintas$ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel master, 1.19.0-2.0.pre.213, on Mac OS X 10.15.4 19E287, locale en-GB)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.6)
> [!] VS Code (version 1.43.2)
>     ✗ Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
>  
> [✓] Connected device (4 available)            
> 
> ! Doctor found issues in 1 category.
> gintas-mac:domukpizzaapp gintas$ flutter build web
> Target file "lib/main.dart" not found.
> gintas-mac:domukpizzaapp gintas$ ./buildweb.sh
> Target dart2js failed: Exception: ../../../flutter/.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart:83:19:
> Error: The getter 'Overflow' isn't defined for the class 'BadgeState'.
>  - 'BadgeState' is from 'package:badges/src/badge.dart'
>  ('../../../flutter/.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart').
>         overflow: Overflow.visible,
>                   ^^^^^^^^
> Error: Compilation failed.
>

**Comment by HakuFlou** [comment]
Same issue, thought it was after I updated my Dart SDK version. Apparently, it's just broken with Flutter 1.19.

Compiler:
```bash
$ flutter build apk

...

Compiler message:
../../../.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart:83:19: Error: The getter 'Overflow' isn't defined for the class 'BadgeState'.
 - 'BadgeState' is from 'package:badges/src/badge.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Overflow'.
        overflow: Overflow.visible,
                  ^^^^^^^^
```

Environment:
```bash
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.213, on Mac OS X 10.15.5 19F96, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by emrekaranfil** [comment]
Hi guys. I just made an update for flutter. There is no problem working right now.

**Flutter version: Flutter 1.19.0-2.0.pre.214 • channel master**

flutter doctor result
````
Flutter 1.19.0-2.0.pre.214 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1d395c5e18 (3 hours ago) • 2020-05-31 07:41:50 -0700
Engine • revision 923687f0e7
Tools • Dart 2.9.0 (build 2.9.0-11.0.dev 6489a0c68d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-2.0.pre.214, on Mac OS X 10.15.5 19F96, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
[✓] VS Code (version 1.45.1)
[!] Connected device
    ! No devices available
````

**Comment by yadaniyil** [comment]
Same

**Comment by softmarshmallow** [comment]
@yadaniyil why would you close this issue?

**Comment by yadaniyil** [comment]
@softmarshmallow I've closed the issue because flutter made a fix on its side. The latest version of the master channel works fine. Let me know if it's not true.

**Comment by radvansky-tomas** [comment]
Not anymore
