### ISSUE TITLE
The getter 'Overflow' isn't defined for the class 'BadgeState'.

### ISSUE THREAD

**Issue by guiiamorim** [yako-dev/flutter_badges#22]
Hi,

I'm getting this error after upgrading to flutter 1.19.0

`Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart:83:19: Error: The getter 'Overflow' isn't defined for the class 'BadgeState'.
 - 'BadgeState' is from 'package:badges/src/badge.dart' ('../../.pub-cache/hosted/pub.dartlang.org/badges-1.1.1/lib/src/badge.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Overflow'.
        overflow: Overflow.visible,
                  ^^^^^^^^`

**Comment by yadaniyil** [comment]
Hi @guiiamorim. Please use `flutter upgrade` and let me know if you still have any issues.

**Comment by guiiamorim** [comment]
Hey @yadaniyil it worked! Thanks a lot.

After running `flutter upgrade` the error disappeared. My current version is:

`Flutter 1.19.0-3.0.pre.13 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6135091de9 (11 hours ago) • 2020-06-01 17:17:03 -0700
Engine • revision e39301f23f
Tools • Dart 2.9.0 (build 2.9.0-13.0.dev 6489a0c68d)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.19.0-3.0.pre.13, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.6)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`
