### ISSUE TITLE
Way to fix size in badge

### ISSUE THREAD

**Issue by omartinma** [yako-dev/flutter_badges#24]
Hi,

I'm using the package to display successive badges in a row with different letters. The problem comes when the letters have different sizes, so the badge take different size as well. Is there a way to define a fix size?

![image](https://user-images.githubusercontent.com/11978998/86464419-c0900d00-bd2f-11ea-892f-f065abe1b2aa.png)

Thanks!

**Comment by rbobko93** [comment]
Same here! Is there a way to set fixed size? I didn't find any way of controlling it.

**Comment by Jarry-Liu** [comment]
> Same here! Is there a way to set fixed size? I didn't find any way of controlling it.

use

```
Badge(
                padding: EdgeInsets.all(3),//the way
                position: BadgePosition.topEnd(top: 1, end: 1),
                badgeContent: null,
                child: Icon(
                  CupertinoIcons.chat_bubble_text,
                  size: 22,
                  color: _homeColorController(),
                ),
              ),
```

**Comment by Jarry-Liu** [comment]
> Same here! Is there a way to set fixed size? I didn't find any way of controlling it.

```
Badge(
                padding: EdgeInsets.all(3),//the way
                position: BadgePosition.topEnd(top: 1, end: 1),
                badgeContent: null,
                child: Icon(
                  CupertinoIcons.chat_bubble_text,
                  size: 22,
                  color: _homeColorController(),
                ),
              ),
```
you can use :padding: EdgeInsets.all(3),
