### ISSUE TITLE
No named parameter with the name 'clipBehavior'.

### ISSUE THREAD

**Issue by Devtue** [yako-dev/flutter_badges#31]
After updating to 1.3.0, I faced this issue.
![Screenshot 2020-10-06 234723](https://user-images.githubusercontent.com/32644439/95246617-5d33e080-0832-11eb-91f7-4c25000b0587.png)

**Comment by savy-91** [comment]
I am facing the same issue, how did you solve it? @Devtue

**Comment by Devtue** [comment]
> I am facing the same issue, how did you solve it? @Devtue

I just used **invalidate Caches / Restart** option in android studio and it worked for me.
