### ISSUE TITLE
parameter with the name 'clipBehavior'.         clipBehavior: Clip.none,         ^^^^^^^^^^^^

### ISSUE THREAD

**Issue by yj229201093** [yako-dev/flutter_badges#38]
![image](https://user-images.githubusercontent.com/12807664/98761634-da91d880-2410-11eb-98be-7c77581ee408.png)
 最新版本1.1.4/ 1.1.3 都会报错

**Comment by Sunsiha** [comment]
@yj229201093 have u got any solution for this?

**Comment by yj229201093** [comment]
> @yj229201093 have u got any solution for this?

I won't. I'm waiting for the bigwigs to sort this out. My version is a 1.17.5 stable version

**Comment by Sunsiha** [comment]
@yj229201093 Oh okay...

**Comment by yj229201093** [comment]
@Sunsiha Upgrading to a higher version of Flutter will solve this problem, but with my current version 1.22.0, this problem is gone.

**Comment by yadaniyil** [comment]
@Sunsiha @yj229201093 you need to update the Flutter version to the `1.22.0` or higher.

**Comment by DTharaka** [comment]
> @Sunsiha @yj229201093 you need to update the Flutter version to the `1.22.0` or higher.

@yadaniyil Is this the only possible solution for this issue? What about the lower versions of the badges package.

**Comment by Anna225** [comment]
I think that it is really good package.
But I can't use without version upgrading.
@yadaniyil  you can't fix it without upgrading?

**Comment by DTharaka** [comment]
> I think that it is really good package.
> But I can't use without version upgrading.
> @yadaniyil you can't fix it without upgrading?

@Anna225 Yes of course, also I'm looking for a possible solution for this. Sometimes, upgrading cause crashes for underdeveloping applications.

**Comment by RusKryzhanovskiy** [comment]
@DTharaka @Anna225 @yj229201093 @Sunsiha 
Temporarily, we will return to the deprecated `overflow` parameter till we find another solution.
Can you check `1.1.6`?

**Comment by DTharaka** [comment]
> @DTharaka @Anna225 @yj229201093 @Sunsiha
> Temporarily, we will return to the deprecated `overflow` parameter till we find another solution.
> Can you check `1.1.6`?

@RusKryzhanovskiy Still same state, no possible solutions also with `v1.1.6` 😶

**Comment by DTharaka** [comment]
It seems the author has a fix for clipBehavior in the latest version 1.1.6. [changelog](https://pub.dev/packages/badges/changelogl). 
@RusKryzhanovskiy @Anna225 @Sunsiha @yj229201093
