### ISSUE TITLE
Outlines clip request 

### ISSUE THREAD

**Issue by rashmisridar** [yako-dev/flutter_badges#39]
In the below code only outline border-color need to black 

` Badge(
                                  badgeColor: Colors.black,
                                  shape: BadgeShape.square,
                                  borderRadius: BorderRadius.circular(20.0),
                 
                                  toAnimate: false,
                                  badgeContent: Text(
                                      'Hi',
                                      style: TextStyle(color: Colors.blue)),
                                )`

**Comment by yadaniyil** [comment]
@rashmisridar sorry for the delay. 
You can use following code (`badges: ^1.1.5` required)

```dart
Badge(
  elevation: 0,
  toAnimate: false,
  shape: BadgeShape.square,
  badgeColor: Colors.transparent,
  borderRadius: BorderRadius.circular(20.0),
  badgeContent: Text('Hi', style: TextStyle(color: Colors.blue)),
  borderSide: BorderSide(color: Colors.black, width: 1),
),
```
