### ISSUE TITLE
Cannot BadgePosition.topCenter or bottomCenter

### ISSUE THREAD

**Issue by JmyW** [yako-dev/flutter_badges#40]
I'm sorry, this is not an issue but request. Could you add "center" besides BadgePosition.topStart, topEnd, bottomStart, bottomEnd?

This is a great library, just hope to add a few feature to be perfect.

**Comment by yadaniyil** [comment]
Hi @JmyW. You can use `position: BadgePosition(),` to set badge to the center of a child. Maybe we will consider adding the "center" option later :)
