### ISSUE TITLE
Migrate overflow: Overflow.visible to clipBehavior: Clip.none

### ISSUE THREAD

**Issue by lehaidangdev** [yako-dev/flutter_badges#42]
I currently use Flutter v1.22.0-12.0.pre and it warning to migrate to Overflow.visible to clipBehavior: Clip.none

`'overflow' is deprecated and shouldn't be used. Use clipBehavior instead. See the migration guide in flutter.dev/go/clip-behavior. This feature was deprecated after v1.22.0-12.0.pre`

**Comment by yadaniyil** [comment]
Hi @lehaidangdev. Thanks, it's fixed in the newest version
