### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by gorillatapstudio** [yako-dev/flutter_badges#46]
When i add the lib to my yaml file, it has the following error
`The current Dart SDK version is 2.12.0-259.12.beta.
Because xxx depends on badge any which requires SDK version >=1.20.1 <=2.1.0, version solving failed.`

How should i solve this or should Badge upgrade anything? thanks!

**Comment by take** [comment]
@gorillatapstudio how did you solve this? 👀
