### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by jonbhanson** [yako-dev/flutter_badges#47]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by bananagag** [comment]
Someone submitted a PR for it #44

**Comment by RusKryzhanovskiy** [comment]
@jonbhanson @bananagag Hi, @miDeb We plan to do it next week.
Thank you for your interest in our package !!!

**Comment by JAICHANGPARK** [comment]
@RusKryzhanovskiy Thank you

**Comment by pr-1** [comment]
Hey Any updates ?

**Comment by fzyzcjy** [comment]
Hi looking forward to this update! Since flutter has make null safety **stable** today!

**Comment by agordeev** [comment]
Flutter 2 is released. Can we get the PR merged ASAP?

**Comment by kuromukira** [comment]
What's the update on this? #44

**Comment by MichalDanielDobrzanski** [comment]
You can always fork this library and adjust it to your own. It is simple and easy to do so.

**Comment by yadaniyil** [comment]
Version 2.0.0 published as prerelease. Please check of everything works as you excected.

**Comment by kuromukira** [comment]
@yadaniyil works as expected for my use case
