### ISSUE TITLE
Gradient Badge

### ISSUE THREAD

**Issue by jordanliu** [yako-dev/flutter_badges#48]
Adding functionality to be able to have a gradient background on a badge. Currently you can only pass a regular colour.

I'd be happy to work on this feature request, or if there are any possible workarounds to get a gradient bg - I'd be open for feedback.

**Comment by RusKryzhanovskiy** [comment]
@jordanliu, sorry for the delay. The `gradient` parameter will be available asap.

Will be available in version `2.0.2`

![Screenshot 2021-07-27 at 16 37 50](https://user-images.githubusercontent.com/25484375/127163604-e6cea043-9249-482d-98e9-420940a58f68.png)
