### ISSUE TITLE
Feature request: option for auto center badge

### ISSUE THREAD

**Issue by f2acode** [yako-dev/flutter_badges#50]
There is the `BadgePosition`, but it's not possible to dynamically center with different child sizes and badge contents.

Here it's a new plugin where it would be very useful: https://github.com/f2acode/pricing_cards

**Comment by RusKryzhanovskiy** [comment]
@f2acode, I'm sorry for the delay. 

The `position: BadgePosition.center(),` will be available in version `2.0.2`
