### ISSUE TITLE
Question: Badge in CupertinoNavigationBar

### ISSUE THREAD

**Issue by robert-virkus** [yako-dev/flutter_badges#53]
Hi,

I am using a badge to indicate a problem on an iOS app. I specify a `leading` parameter in the `CupertinoNavigationBar` like this:

```dart
return CupertinoNavigationBar(
   leading: CupertinoButton(
     child: Badge(child: Text('< Accounts')), 
     onPressed: () {},
   ),
);
```

My  problem now is that the `leading` is truncated. Do you happen to know how I can ensure that the whole widget is shown?
<img width="406" alt="Bildschirmfoto 2021-06-02 um 17 20 29" src="https://user-images.githubusercontent.com/837669/120507296-f8cc1f80-c3c6-11eb-838c-c5fe2f2c974e.png">

Thanks a lot for the help and the great badges project!

**Comment by RusKryzhanovskiy** [comment]
@robert-virkus, sorry for the delay. 
Your code does not work even without the `flutter_badges` package. 
You need to fix it yourself

This isn't related to the package.

![Screenshot 2021-07-27 at 16 20 27](https://user-images.githubusercontent.com/25484375/127160576-4eadd0c5-3974-43cf-bdd5-f5d217435fe8.png)
