### ISSUE TITLE
Feature request - animation for badge appearing/disappearing.

### ISSUE THREAD

**Issue by Justus-M** [yako-dev/flutter_badges#57]

**Comment by yadaniyil** [comment]
Hey @Justus-M. Could you please provide the example of not getting the appearing/disappearing animation? The reason I'm asking is that we have this animation.

**Comment by Justus-M** [comment]
@yadaniyil There is a fade animation for this, so my request was not clear, sorry.

What I meant was modifiable animation for badge appearing disappearing. I.e. being able to specify the BadgeAnimationType for the badge appearing or disappearing. Currently it only seems to use fade, unlike the animation when badgecontent changes.

**Comment by M-ixai-L** [comment]
Hey @Justus-M. <code>Badge</code> have a parameter  <code>animationType</code> to which you can pass <code>BadgeAnimationType[.scale, .fade, .slide]</code>. You can also adjust the duration of the animation with the parameter <code>animationDuration</code>. Isn't that what you're talking about?

**Comment by Justus-M** [comment]
> Hey @Justus-M. <code>Badge</code> have a parameter  <code>animationType</code> to which you can pass <code>BadgeAnimationType[.scale, .fade, .slide]</code>. You can also adjust the duration of the animation with the parameter <code>animationDuration</code>. Isn't that what you're talking about?

That animation only works when you change the badge content, not when the badge appears or disappears. In that case it only shows the fade animation.

**Comment by M-ixai-L** [comment]
> 
Now I understand you, all right, we'll think about your offer. Thank you!

**Comment by M-ixai-L** [comment]
> > Hey @Justus-M. `Badge` have a parameter  `animationType` to which you can pass `BadgeAnimationType[.scale, .fade, .slide]`. You can also adjust the duration of the animation with the parameter `animationDuration`. Isn't that what you're talking about?
> 
> That animation only works when you change the badge content, not when the badge appears or disappears. In that case it only shows the fade animation.
Now I understand you, all right, we'll think about your offer. Thank you!

**Comment by alex-tifox** [comment]
@Justus-M I've faced the same lack of animation customization. 

You could change the `duration` parameter [here](https://github.com/yako-dev/flutter_badges/blob/master/lib/src/badge.dart) of `AnimatedOpacity` on line 207 or 224, or change it to usual `Opacity` if you don't need this hiding animation.

**Comment by yadaniyil** [comment]
Hey @Justus-M @alex-tifox. Please check the new version of the lib here
https://pub.dev/packages/badges/versions/3.0.0-beta.1
Let me know, if your issue still needs some attention in the new version or it's resolved
