### ISSUE TITLE
badgeView AnimateOpacity

### ISSUE THREAD

**Issue by yecheng223** [yako-dev/flutter_badges#67]
Whether the explicit and implicit animation duration of badgeView can be controlled by parameters

![image](https://user-images.githubusercontent.com/28850833/184888701-71931e54-83de-47d6-91e5-64c79661022a.png)

**Comment by kevgug** [comment]
This is a good idea. 200ms is a very long fade animation.

**Comment by yadaniyil** [comment]
Hey @kevgug, thanks for creating the issue. This feature will be available soon when we will publish a new major version of the lib.
