### ISSUE TITLE
Button in badgeContent not work?

### ISSUE THREAD

**Issue by nguyenquanghuy19** [yako-dev/flutter_badges#81]
I have a widget (button) in param badgeContent. When i install the app for the first time, the button doesn't work but when i touch the 3rd time it works.
Can anyone tell me what's wrong with it?

**Comment by yadaniyil** [comment]
@nguyenquanghuy19 please provide the reproducible example

**Comment by nguyenquanghuy19** [comment]
@yadaniyil 
I have a login screen like this:
`Badge(
                position: BadgePosition.bottomStart(bottom: -30.h, start: 70.w),
                badgeContent: _buildSignInBtn(),
                badgeColor: Colors.transparent,
                elevation: 0,
                child: Container(
                  padding: const EdgeInsets.all(20),
                  decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: const BorderRadius.all(
                        Radius.circular(30),
                      ),
                      boxShadow: [
                        BoxShadow(
                          color: HexColors.greyTextField,
                         blurRadius: 5,
                        )
                      ]),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      TextFormField(
                        hintText: "Email Address",
                        controller: viewModel.emailController,
                      ),
                      TextFormField(
                        hintText: "Password,
                        controller: viewModel.passwordController,
                      ),                
                    ],
                  ),
                ),
              ),`

[https://i.ibb.co/6YfhkWR/Untitled.png](url)

**Comment by nguyenquanghuy19** [comment]
Update issue: when i touch the red area the button doesn't work
![Untitled](https://user-images.githubusercontent.com/111052144/203249180-5aa33fd4-392a-4c95-bb7c-3a7e8fbf1982.png)

**Comment by yadaniyil** [comment]
@nguyenquanghuy19 Wow, this is weird usage for the badge, maybe you better use another approach here?
This is how it works in the current version of the badges in the pub.dev (2.0.3). There is no proper onTap for the badge, so you cannot achieve what you want.
But it's already implemented in the dev branch. The onTap for the badge will also be introduced in the new 3.0.0 version and will be published within a week.
